### Ejercicios Numpy

Importar NumPy como np

In [5]:
import numpy as np

Crear un arreglo de 10 ceros

In [ ]:
zeros10 = np.zeros(10)
print(zeros10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Crear un arreglo de 10 unos

In [ ]:
ones10 = np.ones(10)
print(ones10)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Crear un arreglo de 10 sietes

In [ ]:
seven10 = np.ones(10) * 7
print(seven10)

[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]


Crear un arreglo con numeros enteros del 10 al 50

In [6]:
arregloA = np.arange(10,51)
arregloA

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Crear un arreglo con todos los numeros pares del 100 al 500

In [8]:
arregloB = np.arange(100,501,2)
arregloB

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202,
       204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228,
       230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254,
       256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280,
       282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306,
       308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332,
       334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358,
       360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384,
       386, 388, 390, 392, 394, 396, 398, 400, 402, 404, 406, 408, 410,
       412, 414, 416, 418, 420, 422, 424, 426, 428, 430, 432, 434, 436,
       438, 440, 442, 444, 446, 448, 450, 452, 454, 456, 458, 46

Crear una matriz 3x3 con valores del 0 al 8

In [10]:
matrix33 = np.arange(0,9).reshape(3,3)
matrix33

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Crear una matriz de identidad de 3x3

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Utilizar numpy para geneara un numero aleatorio entre 0 y 1

In [18]:
np.random.rand(1)[0]

0.5485690393135035

Utilizar numpy para generar un arreglo de 25 numeros aleatorioas con una distribucion normal

In [22]:
np.random.normal(size=(25,))

array([ 2.21512899, -0.50347849,  0.20725475, -0.42119834, -0.02138694,
        0.80678007,  1.20060736,  0.79056668,  0.85191693,  0.30258097,
       -1.72652843, -1.9182418 , -0.01077987,  0.61747291, -1.37916382,
       -1.46663148, -0.51692879,  1.32156214,  2.66520811, -0.65579773,
       -0.47164095, -0.0154876 , -0.65151507,  0.42899102, -0.15021551])

Crear un arreglo de 50 valores lineales entre 0 y 2

In [24]:
np.random.normal(scale=1,size=(25,))

array([-0.86280297,  0.05285263, -0.39923861, -0.69501797,  1.11961092,
        0.19930599, -0.31334058,  1.40446809,  0.62892032,  0.05096878,
       -1.07453128, -0.46340982,  0.86967938,  1.11551433, -0.96763159,
       -0.99521902, -2.0769263 , -0.43183492, -0.79123246,  0.65189307,
       -1.01896933,  0.7255935 , -0.54003487,  1.47119993,  0.74523019])

## Selección e índices

A continuación se daran varias matrices, se pide replicar el resultado. 

Empieza por definir una matriz de esta forma (llámale "mat"):

![Captura%20de%20Pantalla%202022-09-06%20a%20la%28s%29%2010.59.03.png](attachment:Captura%20de%20Pantalla%202022-09-06%20a%20la%28s%29%2010.59.03.png)

Usando esa matriz, escribe el codigo que permite reproducir el siguiente resultado:

In [ ]:
# se cuidadosa/o al momento de correr el codigo,
# ya que podrias borrar el resultado

![Captura%20de%20Pantalla%202022-09-06%20a%20la%28s%29%2011.03.46.png](attachment:Captura%20de%20Pantalla%202022-09-06%20a%20la%28s%29%2011.03.46.png)

Escribe el código que permite obtener el siguiente resultado:

![Captura%20de%20Pantalla%202022-09-06%20a%20la%28s%29%2011.09.05.png](attachment:Captura%20de%20Pantalla%202022-09-06%20a%20la%28s%29%2011.09.05.png)

Y el siguiente resultado:

![Captura%20de%20Pantalla%202022-09-06%20a%20la%28s%29%2011.10.14.png](attachment:Captura%20de%20Pantalla%202022-09-06%20a%20la%28s%29%2011.10.14.png)

Y éste:

![Captura%20de%20Pantalla%202022-09-06%20a%20la%28s%29%2011.13.59.png](attachment:Captura%20de%20Pantalla%202022-09-06%20a%20la%28s%29%2011.13.59.png)

Por último, escribe el código que permite obtener este resultado:

![Captura%20de%20Pantalla%202022-09-06%20a%20la%28s%29%2011.14.46.png](attachment:Captura%20de%20Pantalla%202022-09-06%20a%20la%28s%29%2011.14.46.png)

Haz lo siguiente

Obten la suma de los valores de "mat"

Obten la desviacion estandar de los valores de "mat"

Obten la suma de las columnas de los valores de mat

### Broadcasting

Dado un arreglo de distancias (en millas) entre las ciudades de la Ruta 66: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff y Los Angeles:

![Captura%20de%20Pantalla%202022-09-12%20a%20la%28s%29%2009.16.03.png](attachment:Captura%20de%20Pantalla%202022-09-12%20a%20la%28s%29%2009.16.03.png)

In [ ]:
mileposts = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])

Genera un arreglo que incluya todas las distancias llamado distance_array

Calcula qué distancias se encuentran a menor distancia y genera un plot que permita visualizar el resultado:

### Fancy indexing

Genera un array con números del 1 al 10 que se llame arr:

Genera una condición que tome números mayores de 4, llámalo mask:

Aplica la máscara (mask) al array:

Ahora usemos matrices. Genera una matriz de ceros de 10x10, llamada arr2d :

Genera un array de índices de la matriz que nos permita después usarlo para hacer subselecciones. Ayuda: para esto será necesaria la longitud.

Selecciona los índices 2,4,6,8 :